#!/usr/bin/with-contenv bash

# make a symbolic link so we can access to the whole conteiner files from the windows emulated GUI
ln -s / /config/computer
chown -v abc:abc /config/computer

# Set up symlinks.
# We need to launch ROMVault from /config as this is where it will write its config.
for f in /opt/romvault/*; do
    ln -fs $f /config/ || true
done


# permissions
chown -R abc:abc \
	/config